# Generated by Django 3.2.9 on 2022-08-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLokasi',
            fields=[
                ('id_lokasi', models.AutoField(db_column='ID_LOKASI', primary_key=True, serialize=False)),
                ('nama_lokasi', models.CharField(db_column='NAMA_LOKASI', max_length=255)),
            ],
            options={
                'db_table': 'master_lokasi',
            },
        ),
        migrations.CreateModel(
            name='MasterPengguna',
            fields=[
                ('id_pengguna', models.CharField(db_column='ID_PENGGUNA', max_length=50, primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(db_column='NAMA_PENGGUNA', max_length=255)),
                ('password_pengguna', models.CharField(db_column='PASSWORD_PENGGUNA', max_length=16)),
                ('jabatan_pengguna', models.IntegerField(db_column='JABATAN_PENGGUNA')),
            ],
            options={
                'db_table': 'master_pengguna',
            },
        ),
        migrations.CreateModel(
            name='MasterInvestasi',
            fields=[
                ('id_investasi', models.AutoField(db_column='ID_INVESTASI', primary_key=True, serialize=False)),
                ('nama_investasi', models.CharField(db_column='NAMA_INVESTASI', max_length=255)),
                ('nilai_investasi', models.DecimalField(db_column='NILAI_INVESTASI', decimal_places=2, max_digits=50)),
                ('pct_investasi', models.DecimalField(db_column='PCT_INVESTASI', decimal_places=2, max_digits=50)),
                ('uraian', models.CharField(db_column='URAIAN', max_length=255)),
                ('tanggal_mulai', models.DateField(db_column='TANGGAL_MULAI')),
                ('tanggal_dibuat', models.DateField(db_column='TANGGAL_DIBUAT')),
                ('status_master_investasi', models.IntegerField(db_column='STATUS_MASTER_INVESTASI')),
                ('status_kunci_investasi', models.IntegerField(db_column='STATUS_KUNCI_INVESTASI')),
                ('id_lokasi', models.ForeignKey(db_column='ID_LOKASI', on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.masterlokasi')),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ID_MANAGER', to='monitoring.masterpengguna')),
                ('id_penanggung_jawab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ID_PENANGGUNG_JAWAB', to='monitoring.masterpengguna')),
            ],
            options={
                'db_table': 'master_investasi',
            },
        ),
        migrations.CreateModel(
            name='DetailInvestasi',
            fields=[
                ('id_detail_investasi', models.AutoField(db_column='ID_DETAIL_INVESTASI', primary_key=True, serialize=False)),
                ('nama_detail_investasi', models.CharField(db_column='NAMA_DETAIL_INVESTASI', max_length=255)),
                ('nilai_detail_investasi', models.DecimalField(db_column='NILAI_DETAIL_INVESTASI', decimal_places=2, max_digits=50)),
                ('uraian', models.CharField(blank=True, db_column='URAIAN', max_length=255, null=True)),
                ('tanggal_mulai_detail_investasi', models.DateField(db_column='TANGGAL_MULAI_DETAIL_INVESTASI')),
                ('tanggal_selesai_detail_investasi', models.DateField(db_column='TANGGAL_SELESAI_DETAIL_INVESTASI')),
                ('tanggal_aktual_selesai_detail_investasi', models.DateField(blank=True, db_column='TANGGAL_AKTUAL_SELESAI_DETAIL_INVESTASI', null=True)),
                ('status_kunci_detail_investasi', models.IntegerField(db_column='STATUS_KUNCI_DETAIL_INVESTASI')),
                ('id_investasi', models.ForeignKey(db_column='ID_INVESTASI', on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.masterinvestasi')),
            ],
            options={
                'db_table': 'detail_investasi',
            },
        ),
        migrations.CreateModel(
            name='DaftarPekerjaan',
            fields=[
                ('id_pekerjaan', models.AutoField(db_column='ID_PEKERJAAN', primary_key=True, serialize=False)),
                ('nama_pekerjaan', models.CharField(db_column='NAMA_PEKERJAAN', max_length=255)),
                ('uraian_pekerjaan', models.CharField(db_column='URAIAN_PEKERJAAN', max_length=255)),
                ('nilai_pekerjaan', models.DecimalField(db_column='NILAI_PEKERJAAN', decimal_places=2, max_digits=50)),
                ('status_pekerjaan', models.IntegerField(db_column='STATUS_PEKERJAAN')),
                ('kunci_pekerjaan', models.IntegerField(db_column='KUNCI_PEKERJAAN')),
                ('nilai_tawaran_pekerjaan', models.DecimalField(db_column='NILAI_TAWARAN_PEKERJAAN', decimal_places=2, max_digits=50)),
                ('tanggal_mulai', models.DateField(db_column='TANGGAL_MULAI')),
                ('tanggal_selesai', models.DateField(blank=True, db_column='TANGGAL_SELESAI', null=True)),
                ('id_detail_investasi', models.ForeignKey(db_column='ID_DETAIL_INVESTASI', on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.detailinvestasi')),
            ],
            options={
                'db_table': 'daftar_pekerjaan',
            },
        ),
    ]
